apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-service
    role: bankops-core
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
  name: auth-service
  namespace: bankops-core
spec:
  ports:
    - name: grpc-port
      port: 50051
      protocol: TCP
      targetPort: 50051
    - name: http-metrics
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: auth-service
    role: bankops-core
  type: ClusterIP
