services:
  gateway-service:
    container_name: gateway-service
    image: shaekhhasan/bankapp-core:gateway-service-v1.0.0
    hostname: gateway-service
    restart: unless-stopped
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - GATEWAY_ENV=prod
      - GATEWAY_GRPC__AUTH_SVC_ADDR=auth-service:50051
      - GATEWAY_GRPC__ACCOUNT_SVC_ADDR=account-service:50051
      - GATEWAY_HTTP__ADDR=:8080
      - GATEWAY_LOGGING__LEVEL=info
      - GATEWAY_LOGGING__ENCODING=console
      - GATEWAY_OBSERVABILITY__METRICS__ENABLED=true
      - GATEWAY_OBSERVABILITY__TRACING__ENABLED=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://gateway-service:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - app-network
    depends_on:
      auth-service:
        condition: service_healthy
      account-service:
        condition: service_healthy
  auth-service:
    image: shaekhhasan/bankapp-core:auth-service-v1.0.0
    container_name: auth-service
    hostname: auth-service
    restart: unless-stopped
    ports:
      - "8081:8080"
    expose:
      - "50051"
      - "8080"
    environment:
      - AUTH_ENV=prod
      - AUTH_GRPC__ADDR=:50051
      - AUTH_HTTP__ADDR=:8080
      - AUTH_LOGGING__LEVEL=info
      - AUTH_LOGGING__ENCODING=console
      - AUTH_OBSERVABILITY__METRICS__ENABLED=true
      - AUTH_OBSERVABILITY__TRACING__ENABLED=false
      - AUTH_AUTH__JWT_TOKEN_DURATION=10m
      - AUTH_DB__TYPE=sqlite
      - AUTH_DB__DSN=/data/auth-service.db
    volumes:
      - ./data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://auth-service:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - app-network
  account-service:
    image: shaekhhasan/bankapp-core:account-service-v1.0.0
    container_name: account-service
    hostname: account-service
    restart: unless-stopped
    ports:
      - "8082:8080"
    expose:
      - "50051"
      - "8080"
    environment:
      - ACCOUNT_ENV=prod
      - ACCOUNT_GRPC__ADDR=:50051
      - ACCOUNT_HTTP__ADDR=:8080
      - ACCOUNT_LOGGING__LEVEL=info
      - ACCOUNT_LOGGING__ENCODING=console
      - ACCOUNT_OBSERVABILITY__METRICS__ENABLED=true
      - ACCOUNT_OBSERVABILITY__TRACING__ENABLED=false
      - ACCOUNT_DB__TYPE=sqlite
      - ACCOUNT_DB__DSN=/data/account-service.db
    volumes:
      - ./data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://account-service:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge