root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/gatewaysvc ./cmd/gatewaysvc"
bin = "./tmp/apigatewaysvc"
full_bin = ""
include_ext = ["go"]
exclude_dir = ["tmp", "vendor"]
delay = 1000

[log]
time = true