version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gocritic
    - revive
  settings:
    revive:
      rules:
        - name: package-comments
          disabled: true

