package error

import "errors"

var (
	ErrCustomerExists                     = errors.New("customer already exists")
	ErrInvalidRequest                     = errors.New("invalid request")
	ErrMissingRequester                   = errors.New("requester missing")
	ErrInvalidAmount                      = errors.New("invalid amount")
	ErrInvalidCustomer                    = errors.New("invalid customer data")
	ErrMissingCustomerID                  = errors.New("customer ID is required")
	ErrNegativeBalance                    = errors.New("balance cannot be negative")
	ErrSameAccountTransfer                = errors.New("cannot transfer to same account")
	ErrMissingReferenceID                 = errors.New("reference ID is required")
	ErrValidationFailed                   = errors.New("validation failed")
	ErrAccountExists                      = errors.New("account already exists")
	ErrInvalidAccount                     = errors.New("invalid account")
	ErrDatabase                           = errors.New("database error")
	ErrTimeout                            = errors.New("operation timeout")
	ErrCustomerNotFound                   = errors.New("customer not found")
	ErrCustomerLocked                     = errors.New("customer is locked for operation")
	ErrFailedToMarkTransactionAsFailed    = errors.New("failed to mark transaction as failed")
	ErrCustomerHasActiveTx                = errors.New("customer has accounts with active transactions")
	ErrConcurrentModification             = errors.New("concurrent modification detected")
	ErrAccountLocked                      = errors.New("account is locked for transaction")
	ErrAccountNotFound                    = errors.New("account not found")
	ErrMissingDestinationAccount          = errors.New("destination account required for transfer")
	ErrInvalidTransactionType             = errors.New("invalid transaction type")
	ErrDuplicateReference                 = errors.New("duplicate transaction reference")
	ErrInvalidWithdrawAmount              = errors.New("withdraw amount must be positive")
	ErrInvalidAddAmount                   = errors.New("add amount must be positive")
	ErrAccountEmpty                       = errors.New("account is already empty")
	ErrTransactionNotFound                = errors.New("transaction not found")
	ErrTransactionCompleted               = errors.New("transaction already completed")
	ErrTransactionFailed                  = errors.New("transaction failed")
	ErrTransactionStatusUpdateFailed      = errors.New("transaction status update failed")
	ErrInsufficientBalance                = errors.New("insufficient balance")
	ErrMissingSourceAccountId             = errors.New("source account id missing")
	ErrMissingDestinationAccountId        = errors.New("destination account id missing")
	ErrMissingAccountInfo                 = errors.New("missing account info")
	ErrAccountValidationFailed            = errors.New("account validation failed")
	ErrAccountDetailsMissing              = errors.New("account details missing")
	ErrAccountLockingFailed               = errors.New("account locking failed")
	ErrAccountUnlockingFailed             = errors.New("account unlocking failed")
	ErrProcessTransactionFailed           = errors.New("process transaction failed")
	ErrProcessTransactionCompletionFailed = errors.New("transaction completion failed")
)
